# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31a97cdd43e7649062a679fce51490dce45668c26b8c3f0363d494d1dddce6bb01d8ccc21a5c5e456143878bbfcfea3ff3bdb878195af17c5aa9639ab9752505

test:
  secret_key_base: e9e8180005f8315ec66048c5e27da16e09fbd12dae4430fe35006ecd92dbc2c6f35054e65b56a83d6d6e53e7e2ad0192722f7881d21b0950e3d5ab1f19b2b427

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
